// ------------------------------------------------------------
// fatori_reg_mon.svh
// auto-generated by fatori-v.py (fatori_mon.py)
// ------------------------------------------------------------

`ifndef FATORI_REG_MON_SVH
`define FATORI_REG_MON_SVH


// fatori_fault_mgr.sv
`define minor_cnt_o_MON_N 1
`define minor_cnt_o_MON_M 0
`define minor_cnt_o_HOLD_LAST_GOOD 0

`define major_cnt_o_MON_N 1
`define major_cnt_o_MON_M 0
`define major_cnt_o_HOLD_LAST_GOOD 0

`define minor_seen_o_MON_N 1
`define minor_seen_o_MON_M 0
`define minor_seen_o_HOLD_LAST_GOOD 0

`define fault_sticky_o_MON_N 1
`define fault_sticky_o_MON_M 0
`define fault_sticky_o_HOLD_LAST_GOOD 0

`define fetch_en_q_MON_N 1
`define fetch_en_q_MON_M 0
`define fetch_en_q_HOLD_LAST_GOOD 0

`define state_q_MON_N 1
`define state_q_MON_M 0
`define state_q_HOLD_LAST_GOOD 0

`define corrected_cnt_q_MON_N 1
`define corrected_cnt_q_MON_M 0
`define corrected_cnt_q_HOLD_LAST_GOOD 0

`define cycle_counter_q_MON_N 1
`define cycle_counter_q_MON_M 0
`define cycle_counter_q_HOLD_LAST_GOOD 0

`define first_min_latched_q_MON_N 1
`define first_min_latched_q_MON_M 0
`define first_min_latched_q_HOLD_LAST_GOOD 0

`define cycles_to_first_min_q_MON_N 1
`define cycles_to_first_min_q_MON_M 0
`define cycles_to_first_min_q_HOLD_LAST_GOOD 0

`define first_maj_latched_q_MON_N 1
`define first_maj_latched_q_MON_M 0
`define first_maj_latched_q_HOLD_LAST_GOOD 0

`define cycles_to_first_maj_q_MON_N 1
`define cycles_to_first_maj_q_MON_M 0
`define cycles_to_first_maj_q_HOLD_LAST_GOOD 0

`define last_injection_cycle_q_MON_N 1
`define last_injection_cycle_q_MON_M 0
`define last_injection_cycle_q_HOLD_LAST_GOOD 0

`define last_detection_latency_q_MON_N 1
`define last_detection_latency_q_MON_M 0
`define last_detection_latency_q_HOLD_LAST_GOOD 0

`define latency_sum_q_MON_N 1
`define latency_sum_q_MON_M 0
`define latency_sum_q_HOLD_LAST_GOOD 0

`define latency_count_q_MON_N 1
`define latency_count_q_MON_M 0
`define latency_count_q_HOLD_LAST_GOOD 0


// ibex_controller.sv
`define mem_resp_intg_err_irq_pending_q_MON_N 1
`define mem_resp_intg_err_irq_pending_q_MON_M 0
`define mem_resp_intg_err_irq_pending_q_HOLD_LAST_GOOD 0

`define mem_resp_intg_err_addr_q_MON_N 1
`define mem_resp_intg_err_addr_q_MON_M 0
`define mem_resp_intg_err_addr_q_HOLD_LAST_GOOD 0

`define debug_cause_q_MON_N 1
`define debug_cause_q_MON_M 0
`define debug_cause_q_HOLD_LAST_GOOD 0

`define ctrl_fsm_cs_MON_N 1
`define ctrl_fsm_cs_MON_M 0
`define ctrl_fsm_cs_HOLD_LAST_GOOD 0

`define nmi_mode_q_MON_N 1
`define nmi_mode_q_MON_M 0
`define nmi_mode_q_HOLD_LAST_GOOD 0

`define do_single_step_q_MON_N 1
`define do_single_step_q_MON_M 0
`define do_single_step_q_HOLD_LAST_GOOD 0

`define debug_mode_q_MON_N 1
`define debug_mode_q_MON_M 0
`define debug_mode_q_HOLD_LAST_GOOD 0

`define enter_debug_mode_prio_q_MON_N 1
`define enter_debug_mode_prio_q_MON_M 0
`define enter_debug_mode_prio_q_HOLD_LAST_GOOD 0

`define load_err_q_MON_N 1
`define load_err_q_MON_M 0
`define load_err_q_HOLD_LAST_GOOD 0

`define store_err_q_MON_N 1
`define store_err_q_MON_M 0
`define store_err_q_HOLD_LAST_GOOD 0

`define exc_req_q_MON_N 1
`define exc_req_q_MON_M 0
`define exc_req_q_HOLD_LAST_GOOD 0

`define illegal_insn_q_MON_N 1
`define illegal_insn_q_MON_M 0
`define illegal_insn_q_HOLD_LAST_GOOD 0


// ibex_core.sv
`define last_fetch_enable_MON_N 1
`define last_fetch_enable_MON_M 0
`define last_fetch_enable_HOLD_LAST_GOOD 0

`define pc_at_fetch_disable_MON_N 1
`define pc_at_fetch_disable_MON_M 0
`define pc_at_fetch_disable_HOLD_LAST_GOOD 0

`define rvfi_instr_new_wb_q_MON_N 1
`define rvfi_instr_new_wb_q_MON_M 0
`define rvfi_instr_new_wb_q_HOLD_LAST_GOOD 0

`define captured_valid_MON_N 1
`define captured_valid_MON_M 0
`define captured_valid_HOLD_LAST_GOOD 0

`define captured_mip_MON_N 1
`define captured_mip_MON_M 0
`define captured_mip_HOLD_LAST_GOOD 0

`define captured_nmi_MON_N 1
`define captured_nmi_MON_M 0
`define captured_nmi_HOLD_LAST_GOOD 0

`define captured_nmi_int_MON_N 1
`define captured_nmi_int_MON_M 0
`define captured_nmi_int_HOLD_LAST_GOOD 0

`define captured_debug_req_MON_N 1
`define captured_debug_req_MON_M 0
`define captured_debug_req_HOLD_LAST_GOOD 0

`define rvfi_irq_valid_MON_N 1
`define rvfi_irq_valid_MON_M 0
`define rvfi_irq_valid_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_pre_mip_0_MON_N 1
`define rvfi_ext_stage_pre_mip_0_MON_M 0
`define rvfi_ext_stage_pre_mip_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_nmi_0_MON_N 1
`define rvfi_ext_stage_nmi_0_MON_M 0
`define rvfi_ext_stage_nmi_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_nmi_int_0_MON_N 1
`define rvfi_ext_stage_nmi_int_0_MON_M 0
`define rvfi_ext_stage_nmi_int_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_debug_req_0_MON_N 1
`define rvfi_ext_stage_debug_req_0_MON_M 0
`define rvfi_ext_stage_debug_req_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_irq_valid_0_MON_N 1
`define rvfi_ext_stage_irq_valid_0_MON_M 0
`define rvfi_ext_stage_irq_valid_0_HOLD_LAST_GOOD 0

`define rvfi_stage_halt_reg_0_MON_N 1
`define rvfi_stage_halt_reg_0_MON_M 0
`define rvfi_stage_halt_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_trap_reg_0_MON_N 1
`define rvfi_stage_trap_reg_0_MON_M 0
`define rvfi_stage_trap_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_intr_reg_0_MON_N 1
`define rvfi_stage_intr_reg_0_MON_M 0
`define rvfi_stage_intr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_order_reg_0_MON_N 1
`define rvfi_stage_order_reg_0_MON_M 0
`define rvfi_stage_order_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_insn_reg_0_MON_N 1
`define rvfi_stage_insn_reg_0_MON_M 0
`define rvfi_stage_insn_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mode_reg_0_MON_N 1
`define rvfi_stage_mode_reg_0_MON_M 0
`define rvfi_stage_mode_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_ixl_reg_0_MON_N 1
`define rvfi_stage_ixl_reg_0_MON_M 0
`define rvfi_stage_ixl_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs1_addr_reg_0_MON_N 1
`define rvfi_stage_rs1_addr_reg_0_MON_M 0
`define rvfi_stage_rs1_addr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs2_addr_reg_0_MON_N 1
`define rvfi_stage_rs2_addr_reg_0_MON_M 0
`define rvfi_stage_rs2_addr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs3_addr_reg_0_MON_N 1
`define rvfi_stage_rs3_addr_reg_0_MON_M 0
`define rvfi_stage_rs3_addr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_pc_rdata_reg_0_MON_N 1
`define rvfi_stage_pc_rdata_reg_0_MON_M 0
`define rvfi_stage_pc_rdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_pc_wdata_reg_0_MON_N 1
`define rvfi_stage_pc_wdata_reg_0_MON_M 0
`define rvfi_stage_pc_wdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mem_rmask_reg_0_MON_N 1
`define rvfi_stage_mem_rmask_reg_0_MON_M 0
`define rvfi_stage_mem_rmask_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mem_wmask_reg_0_MON_N 1
`define rvfi_stage_mem_wmask_reg_0_MON_M 0
`define rvfi_stage_mem_wmask_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs1_rdata_reg_0_MON_N 1
`define rvfi_stage_rs1_rdata_reg_0_MON_M 0
`define rvfi_stage_rs1_rdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs2_rdata_reg_0_MON_N 1
`define rvfi_stage_rs2_rdata_reg_0_MON_M 0
`define rvfi_stage_rs2_rdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rs3_rdata_reg_0_MON_N 1
`define rvfi_stage_rs3_rdata_reg_0_MON_M 0
`define rvfi_stage_rs3_rdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mem_wdata_reg_0_MON_N 1
`define rvfi_stage_mem_wdata_reg_0_MON_M 0
`define rvfi_stage_mem_wdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mem_addr_reg_0_MON_N 1
`define rvfi_stage_mem_addr_reg_0_MON_M 0
`define rvfi_stage_mem_addr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rd_addr_reg_0_MON_N 1
`define rvfi_stage_rd_addr_reg_0_MON_M 0
`define rvfi_stage_rd_addr_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_rd_wdata_reg_0_MON_N 1
`define rvfi_stage_rd_wdata_reg_0_MON_M 0
`define rvfi_stage_rd_wdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_stage_mem_rdata_reg_0_MON_N 1
`define rvfi_stage_mem_rdata_reg_0_MON_M 0
`define rvfi_stage_mem_rdata_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_debug_mode_reg_0_MON_N 1
`define rvfi_ext_stage_debug_mode_reg_0_MON_M 0
`define rvfi_ext_stage_debug_mode_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mcycle_reg_0_MON_N 1
`define rvfi_ext_stage_mcycle_reg_0_MON_M 0
`define rvfi_ext_stage_mcycle_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_ic_scr_key_valid_reg_0_MON_N 1
`define rvfi_ext_stage_ic_scr_key_valid_reg_0_MON_M 0
`define rvfi_ext_stage_ic_scr_key_valid_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_0_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_0_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_0_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_0_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_0_HOLD_LAST_GOOD 0

`define rvfi_stage_valid_reg_0_MON_N 1
`define rvfi_stage_valid_reg_0_MON_M 0
`define rvfi_stage_valid_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_pre_mip_reg_0_MON_N 1
`define rvfi_ext_stage_pre_mip_reg_0_MON_M 0
`define rvfi_ext_stage_pre_mip_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_post_mip_reg_0_MON_N 1
`define rvfi_ext_stage_post_mip_reg_0_MON_M 0
`define rvfi_ext_stage_post_mip_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_nmi_reg_0_MON_N 1
`define rvfi_ext_stage_nmi_reg_0_MON_M 0
`define rvfi_ext_stage_nmi_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_nmi_int_reg_0_MON_N 1
`define rvfi_ext_stage_nmi_int_reg_0_MON_M 0
`define rvfi_ext_stage_nmi_int_reg_0_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_debug_req_reg_0_MON_N 1
`define rvfi_ext_stage_debug_req_reg_0_MON_M 0
`define rvfi_ext_stage_debug_req_reg_0_HOLD_LAST_GOOD 0

`define rvfi_mem_addr_MON_N 1
`define rvfi_mem_addr_MON_M 0
`define rvfi_mem_addr_HOLD_LAST_GOOD 0

`define rvfi_mem_rdata_MON_N 1
`define rvfi_mem_rdata_MON_M 0
`define rvfi_mem_rdata_HOLD_LAST_GOOD 0

`define rvfi_mem_wdata_MON_N 1
`define rvfi_mem_wdata_MON_M 0
`define rvfi_mem_wdata_HOLD_LAST_GOOD 0

`define rvfi_rs1_data_MON_N 1
`define rvfi_rs1_data_MON_M 0
`define rvfi_rs1_data_HOLD_LAST_GOOD 0

`define rvfi_rs1_addr_MON_N 1
`define rvfi_rs1_addr_MON_M 0
`define rvfi_rs1_addr_HOLD_LAST_GOOD 0

`define rvfi_rs2_data_MON_N 1
`define rvfi_rs2_data_MON_M 0
`define rvfi_rs2_data_HOLD_LAST_GOOD 0

`define rvfi_rs2_addr_MON_N 1
`define rvfi_rs2_addr_MON_M 0
`define rvfi_rs2_addr_HOLD_LAST_GOOD 0

`define rvfi_rd_addr_q_MON_N 1
`define rvfi_rd_addr_q_MON_M 0
`define rvfi_rd_addr_q_HOLD_LAST_GOOD 0

`define rvfi_rd_wdata_q_MON_N 1
`define rvfi_rd_wdata_q_MON_M 0
`define rvfi_rd_wdata_q_HOLD_LAST_GOOD 0

`define rvfi_set_trap_pc_MON_N 1
`define rvfi_set_trap_pc_MON_M 0
`define rvfi_set_trap_pc_HOLD_LAST_GOOD 0

`define rvfi_intr_MON_N 1
`define rvfi_intr_MON_M 0
`define rvfi_intr_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_1_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_1_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_1_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_2_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_2_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_2_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_3_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_3_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_3_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_4_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_4_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_4_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_5_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_5_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_5_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_6_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_6_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_6_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_7_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_7_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_7_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_8_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_8_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_8_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcounters_reg_0_9_MON_N 1
`define rvfi_ext_stage_mhpmcounters_reg_0_9_MON_M 0
`define rvfi_ext_stage_mhpmcounters_reg_0_9_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_1_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_1_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_1_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_2_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_2_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_2_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_3_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_3_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_3_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_4_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_4_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_4_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_5_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_5_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_5_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_6_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_6_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_6_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_7_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_7_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_7_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_8_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_8_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_8_HOLD_LAST_GOOD 0

`define rvfi_ext_stage_mhpmcountersh_reg_0_9_MON_N 1
`define rvfi_ext_stage_mhpmcountersh_reg_0_9_MON_M 0
`define rvfi_ext_stage_mhpmcountersh_reg_0_9_HOLD_LAST_GOOD 0


// ibex_cs_registers.sv
`define mcountinhibit_MON_N 1
`define mcountinhibit_MON_M 0
`define mcountinhibit_HOLD_LAST_GOOD 0

`define priv_lvl_q_MON_N 1
`define priv_lvl_q_MON_M 0
`define priv_lvl_q_HOLD_LAST_GOOD 0


// ibex_csr.sv
`define rdata_MON_N 1
`define rdata_MON_M 0
`define rdata_HOLD_LAST_GOOD 0

`define shadow_MON_N 1
`define shadow_MON_M 0
`define shadow_HOLD_LAST_GOOD 0


// ibex_decoder.sv
`define use_rs3_MON_N 1
`define use_rs3_MON_M 0
`define use_rs3_HOLD_LAST_GOOD 0


// ibex_dummy_instr.sv
`define dummy_instr_seed_MON_N 1
`define dummy_instr_seed_MON_M 0
`define dummy_instr_seed_HOLD_LAST_GOOD 0

`define dummy_cnt_MON_N 1
`define dummy_cnt_MON_M 0
`define dummy_cnt_HOLD_LAST_GOOD 0


// ibex_fetch_fifo.sv
`define instr_addr_MON_N 1
`define instr_addr_MON_M 0
`define instr_addr_HOLD_LAST_GOOD 0

`define instr_addr_no_rst_MON_N 1
`define instr_addr_no_rst_MON_M 0
`define instr_addr_no_rst_HOLD_LAST_GOOD 0

`define valid_MON_N 1
`define valid_MON_M 0
`define valid_HOLD_LAST_GOOD 0

`define rdata_0_MON_N 1
`define rdata_0_MON_M 0
`define rdata_0_HOLD_LAST_GOOD 0

`define err_0_MON_N 1
`define err_0_MON_M 0
`define err_0_HOLD_LAST_GOOD 0

`define rdata_1_MON_N 1
`define rdata_1_MON_M 0
`define rdata_1_HOLD_LAST_GOOD 0

`define err_1_MON_N 1
`define err_1_MON_M 0
`define err_1_HOLD_LAST_GOOD 0

`define rdata_2_MON_N 1
`define rdata_2_MON_M 0
`define rdata_2_HOLD_LAST_GOOD 0

`define err_2_MON_N 1
`define err_2_MON_M 0
`define err_2_HOLD_LAST_GOOD 0


// ibex_id_stage.sv
`define imd_val_q_reg_0_MON_N 1
`define imd_val_q_reg_0_MON_M 0
`define imd_val_q_reg_0_HOLD_LAST_GOOD 0

`define imd_val_q_reg_1_MON_N 1
`define imd_val_q_reg_1_MON_M 0
`define imd_val_q_reg_1_HOLD_LAST_GOOD 0

`define branch_set_raw_MON_N 1
`define branch_set_raw_MON_M 0
`define branch_set_raw_HOLD_LAST_GOOD 0

`define branch_jump_set_done_MON_N 1
`define branch_jump_set_done_MON_M 0
`define branch_jump_set_done_HOLD_LAST_GOOD 0

`define branch_taken_MON_N 1
`define branch_taken_MON_M 0
`define branch_taken_HOLD_LAST_GOOD 0

`define id_fsm_q_MON_N 1
`define id_fsm_q_MON_M 0
`define id_fsm_q_HOLD_LAST_GOOD 0


// ibex_if_stage.sv
`define dummy_instr_id_MON_N 1
`define dummy_instr_id_MON_M 0
`define dummy_instr_id_HOLD_LAST_GOOD 0

`define instr_valid_id_q_reg_MON_N 1
`define instr_valid_id_q_reg_MON_M 0
`define instr_valid_id_q_reg_HOLD_LAST_GOOD 0

`define instr_new_id_q_reg_MON_N 1
`define instr_new_id_q_reg_MON_M 0
`define instr_new_id_q_reg_HOLD_LAST_GOOD 0

`define instr_rdata_id_MON_N 1
`define instr_rdata_id_MON_M 0
`define instr_rdata_id_HOLD_LAST_GOOD 0

`define instr_rdata_alu_id_MON_N 1
`define instr_rdata_alu_id_MON_M 0
`define instr_rdata_alu_id_HOLD_LAST_GOOD 0

`define instr_fetch_err_MON_N 1
`define instr_fetch_err_MON_M 0
`define instr_fetch_err_HOLD_LAST_GOOD 0

`define instr_fetch_err_plus2_MON_N 1
`define instr_fetch_err_plus2_MON_M 0
`define instr_fetch_err_plus2_HOLD_LAST_GOOD 0

`define instr_rdata_c_id_MON_N 1
`define instr_rdata_c_id_MON_M 0
`define instr_rdata_c_id_HOLD_LAST_GOOD 0

`define instr_is_compressed_id_MON_N 1
`define instr_is_compressed_id_MON_M 0
`define instr_is_compressed_id_HOLD_LAST_GOOD 0

`define illegal_c_insn_id_MON_N 1
`define illegal_c_insn_id_MON_M 0
`define illegal_c_insn_id_HOLD_LAST_GOOD 0

`define pc_id_MON_N 1
`define pc_id_MON_M 0
`define pc_id_HOLD_LAST_GOOD 0

`define instr_rdata_id_no_rst_MON_N 1
`define instr_rdata_id_no_rst_MON_M 0
`define instr_rdata_id_no_rst_HOLD_LAST_GOOD 0

`define instr_rdata_alu_id_no_rst_MON_N 1
`define instr_rdata_alu_id_no_rst_MON_M 0
`define instr_rdata_alu_id_no_rst_HOLD_LAST_GOOD 0

`define instr_fetch_err_no_rst_MON_N 1
`define instr_fetch_err_no_rst_MON_M 0
`define instr_fetch_err_no_rst_HOLD_LAST_GOOD 0

`define instr_fetch_err_plus2_no_rst_MON_N 1
`define instr_fetch_err_plus2_no_rst_MON_M 0
`define instr_fetch_err_plus2_no_rst_HOLD_LAST_GOOD 0

`define instr_rdata_c_id_MON_N 1
`define instr_rdata_c_id_MON_M 0
`define instr_rdata_c_id_HOLD_LAST_GOOD 0

`define instr_is_compressed_id_no_rst_MON_N 1
`define instr_is_compressed_id_no_rst_MON_M 0
`define instr_is_compressed_id_no_rst_HOLD_LAST_GOOD 0

`define illegal_c_insn_id_no_rst_MON_N 1
`define illegal_c_insn_id_no_rst_MON_M 0
`define illegal_c_insn_id_no_rst_HOLD_LAST_GOOD 0

`define pc_id_MON_N 1
`define pc_id_MON_M 0
`define pc_id_HOLD_LAST_GOOD 0

`define prev_instr_seq_MON_N 1
`define prev_instr_seq_MON_M 0
`define prev_instr_seq_HOLD_LAST_GOOD 0

`define instr_bp_taken_MON_N 1
`define instr_bp_taken_MON_M 0
`define instr_bp_taken_HOLD_LAST_GOOD 0

`define instr_bp_taken_no_rst_MON_N 1
`define instr_bp_taken_no_rst_MON_M 0
`define instr_bp_taken_no_rst_HOLD_LAST_GOOD 0

`define instr_skid_valid_q_MON_N 1
`define instr_skid_valid_q_MON_M 0
`define instr_skid_valid_q_HOLD_LAST_GOOD 0

`define instr_skid_bp_taken_q_MON_N 1
`define instr_skid_bp_taken_q_MON_M 0
`define instr_skid_bp_taken_q_HOLD_LAST_GOOD 0

`define instr_skid_data_q_MON_N 1
`define instr_skid_data_q_MON_M 0
`define instr_skid_data_q_HOLD_LAST_GOOD 0

`define instr_skid_addr_q_MON_N 1
`define instr_skid_addr_q_MON_M 0
`define instr_skid_addr_q_HOLD_LAST_GOOD 0

`define instr_skid_bp_taken_q_no_rst_MON_N 1
`define instr_skid_bp_taken_q_no_rst_MON_M 0
`define instr_skid_bp_taken_q_no_rst_HOLD_LAST_GOOD 0

`define instr_skid_data_q_no_rst_MON_N 1
`define instr_skid_data_q_no_rst_MON_M 0
`define instr_skid_data_q_no_rst_HOLD_LAST_GOOD 0

`define instr_skid_addr_q_no_rst_MON_N 1
`define instr_skid_addr_q_no_rst_MON_M 0
`define instr_skid_addr_q_no_rst_HOLD_LAST_GOOD 0


// ibex_load_store_unit.sv
`define rdata_MON_N 1
`define rdata_MON_M 0
`define rdata_HOLD_LAST_GOOD 0

`define rdata_offset_MON_N 1
`define rdata_offset_MON_M 0
`define rdata_offset_HOLD_LAST_GOOD 0

`define data_type_MON_N 1
`define data_type_MON_M 0
`define data_type_HOLD_LAST_GOOD 0

`define data_sign_ext_MON_N 1
`define data_sign_ext_MON_M 0
`define data_sign_ext_HOLD_LAST_GOOD 0

`define data_we_MON_N 1
`define data_we_MON_M 0
`define data_we_HOLD_LAST_GOOD 0

`define addr_last_MON_N 1
`define addr_last_MON_M 0
`define addr_last_HOLD_LAST_GOOD 0

`define ls_fsm_cs_MON_N 1
`define ls_fsm_cs_MON_M 0
`define ls_fsm_cs_HOLD_LAST_GOOD 0

`define handle_misaligned_MON_N 1
`define handle_misaligned_MON_M 0
`define handle_misaligned_HOLD_LAST_GOOD 0

`define pmp_err_MON_N 1
`define pmp_err_MON_M 0
`define pmp_err_HOLD_LAST_GOOD 0

`define lsu_err_MON_N 1
`define lsu_err_MON_M 0
`define lsu_err_HOLD_LAST_GOOD 0

`define fcov_mis_2_en_MON_N 1
`define fcov_mis_2_en_MON_M 0
`define fcov_mis_2_en_HOLD_LAST_GOOD 0

`define fcov_mis_bus_err_1_MON_N 1
`define fcov_mis_bus_err_1_MON_M 0
`define fcov_mis_bus_err_1_HOLD_LAST_GOOD 0


// ibex_lockstep.sv
`define shadow_inputs_0_MON_N 1
`define shadow_inputs_0_MON_M 0
`define shadow_inputs_0_HOLD_LAST_GOOD 0

`define shadow_inputs_1_MON_N 1
`define shadow_inputs_1_MON_M 0
`define shadow_inputs_1_HOLD_LAST_GOOD 0

`define shadow_tag_rdata_0_MON_N 1
`define shadow_tag_rdata_0_MON_M 0
`define shadow_tag_rdata_0_HOLD_LAST_GOOD 0

`define shadow_data_rdata_0_MON_N 1
`define shadow_data_rdata_0_MON_M 0
`define shadow_data_rdata_0_HOLD_LAST_GOOD 0

`define shadow_tag_rdata_1_MON_N 1
`define shadow_tag_rdata_1_MON_M 0
`define shadow_tag_rdata_1_HOLD_LAST_GOOD 0

`define shadow_data_rdata_1_MON_N 1
`define shadow_data_rdata_1_MON_M 0
`define shadow_data_rdata_1_HOLD_LAST_GOOD 0


// ibex_prefetch_buffer.sv
`define stored_addr_MON_N 1
`define stored_addr_MON_M 0
`define stored_addr_HOLD_LAST_GOOD 0

`define fetch_addr_MON_N 1
`define fetch_addr_MON_M 0
`define fetch_addr_HOLD_LAST_GOOD 0

`define valid_req_MON_N 1
`define valid_req_MON_M 0
`define valid_req_HOLD_LAST_GOOD 0

`define discard_req_MON_N 1
`define discard_req_MON_M 0
`define discard_req_HOLD_LAST_GOOD 0

`define rdata_outstanding_MON_N 1
`define rdata_outstanding_MON_M 0
`define rdata_outstanding_HOLD_LAST_GOOD 0

`define branch_discard_MON_N 1
`define branch_discard_MON_M 0
`define branch_discard_HOLD_LAST_GOOD 0


// ibex_top.sv
`define core_busy_MON_N 1
`define core_busy_MON_M 0
`define core_busy_HOLD_LAST_GOOD 0

`define scramble_key_MON_N 1
`define scramble_key_MON_M 0
`define scramble_key_HOLD_LAST_GOOD 0

`define scramble_nonce_MON_N 1
`define scramble_nonce_MON_M 0
`define scramble_nonce_HOLD_LAST_GOOD 0

`define scramble_key_valid_MON_N 1
`define scramble_key_valid_MON_M 0
`define scramble_key_valid_HOLD_LAST_GOOD 0

`define scramble_req_MON_N 1
`define scramble_req_MON_M 0
`define scramble_req_HOLD_LAST_GOOD 0

`define sampled_scramble_key_MON_N 1
`define sampled_scramble_key_MON_M 0
`define sampled_scramble_key_HOLD_LAST_GOOD 0

`define pending_dside_accesses_0_MON_N 1
`define pending_dside_accesses_0_MON_M 0
`define pending_dside_accesses_0_HOLD_LAST_GOOD 0

`define pending_dside_accesses_1_MON_N 1
`define pending_dside_accesses_1_MON_M 0
`define pending_dside_accesses_1_HOLD_LAST_GOOD 0


// ibex_wb_stage.sv
`define wb_valid_MON_N 1
`define wb_valid_MON_M 0
`define wb_valid_HOLD_LAST_GOOD 0

`define rf_we_wb_MON_N 1
`define rf_we_wb_MON_M 0
`define rf_we_wb_HOLD_LAST_GOOD 0

`define rf_waddr_wb_MON_N 1
`define rf_waddr_wb_MON_M 0
`define rf_waddr_wb_HOLD_LAST_GOOD 0

`define rf_wdata_wb_MON_N 1
`define rf_wdata_wb_MON_M 0
`define rf_wdata_wb_HOLD_LAST_GOOD 0

`define wb_instr_type_MON_N 1
`define wb_instr_type_MON_M 0
`define wb_instr_type_HOLD_LAST_GOOD 0

`define wb_pc_MON_N 1
`define wb_pc_MON_M 0
`define wb_pc_HOLD_LAST_GOOD 0

`define wb_compressed_MON_N 1
`define wb_compressed_MON_M 0
`define wb_compressed_HOLD_LAST_GOOD 0

`define wb_count_MON_N 1
`define wb_count_MON_M 0
`define wb_count_HOLD_LAST_GOOD 0

`define dummy_instr_wb_MON_N 1
`define dummy_instr_wb_MON_M 0
`define dummy_instr_wb_HOLD_LAST_GOOD 0



`endif // FATORI_REG_MON_SVH